name: Deploy
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch deps
      run: yarn
    - name: Build
      run: yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: Setup CNAME
      run: cp CNAME ./dist/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
