name: Deploy
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch deps
      run: yarn
    - name: Build
      run: yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
